### ISSUE TITLE
Apple

### ISSUE THREAD

**Issue by polzy** [SVendittelli/MMM-fitbit#3]
Hi, 
Very god job,
It's possible to getting apple watch or iPhone data with Health app or other app ?

**Comment by CFenner** [comment]
Good idea, I would also be interested. But I think Apple is much more restrictive...

**Comment by SVendittelli** [comment]
I believe healthkit data is only stored locally on your device so you'd have to export it manually and convert it.

I guess you could write an iOS app to do that automatically and upload it to Dropbox or something but that's way beyond me!

**Comment by SVendittelli** [comment]
http://apple.stackexchange.com/questions/167671/view-ios-health-data-externally
