### ISSUE TITLE
Error executing MMM-fitbit

### ISSUE THREAD

**Issue by greppie** [SVendittelli/MMM-fitbit#4]
I installed MMM-fitbit and all dependencies and registered an new application to use fitbit API.
fitbit-API generates:

- OAuth 2.0 Client ID
- Client Secret
- OAuth 2.0: Authorization URI
- OAuth 2.0: Access/Refresh Token Request URI
but **NO key!**

Output from script
`results: [{"message":"Writing credentials to credentials.ini","type":"status"},{"message":"Writing id: <myid>, key: , and secret: <mysecret>","type":"status"},{"message":"Credentials write successful","type":"status"}]`
id and secret set correctly.

If I run the module I get the error:
`Whoops! There was an uncaught exception...
{ [Error: process exited with code 1]
  executable: 'python',
  options: null,
  script: 'modules/MMM-fitbit/python/getData.py',
  args: null,
  exitCode: 1 }
`
How can I debug what I'll get from getDate.py? I'm new to python and `print ""` or `sys.stdout.write()` does not work in getData.py

Cheers
greppie

**Comment by SVendittelli** [comment]
Fitbit seems to have changed the way their OAuth works slightly, I'll try to make a hotfix today

**Comment by SVendittelli** [comment]
I believe it is fixed now, can you give it a try?

**Comment by greppie** [comment]
Thanks for the fast response.

Not yet ... but get another issue. At first you need to fix `iniHandler.py` at last line - `WriteCredentials(sys.argv[1],sys.argv[2],sys.argv[3])` gives three areguments, but only 2 needed.

After fixing this I get the error:
`results: [{"message":"Writing credentials to credentials.ini","type":"status"},{"message":"Writing id: <correctID> and secret: ","type":"status"},{"message":"Credentials write successful","type":"status"}]
`

`Whoops! There was an uncaught exception...
{ Error: process exited with code 1
    at terminateIfNeeded (/home/fgrep/MagicMirror/modules/node_modules/python-shell/index.js:100:23)
    at ChildProcess.<anonymous> (/home/fgrep/MagicMirror/modules/node_modules/python-shell/index.js:88:9)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
  executable: 'python',
  options: null,
  script: 'modules/MMM-fitbit/python/getData.py',
  args: null,
  exitCode: 1 }
`

`MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
`

I'm wondering about the secret in the status message above - ist this correct?
Second thing I forgot to tell in the first issue description: in the README you tell 
`<snip>Run setupFitbit.py in the python directory. You can either</snip>`

But there's no setupFitbit.py Using setupAccess.py throws a lot of exceptions due to your fix. I setup both ini-files manually but still got the above error.

Any ideas?

**Comment by SVendittelli** [comment]
My node helper was passing a null argument for key and python was throwing a fit, it should be fixed now (he says hoping). Trying to deal with it in between revising for exams!

**Comment by greppie** [comment]
Now it works! Thanks for your help. Would be very nice if you hande authentication errors and give a message about the error. Took me while to realize my tokens are invalid.

Next thing ist, that setupAccess.py doesnt work or I did not understood how it does. The script start a server at port 8080 but if fitbit redirects to it I get an error that the page is not accessible. However I copied the token from url an put it into tokens.ini. There's only an access token and no refresh token, right?

Cheers
greppie

BTW: Best luck with your exams!

**Comment by greppie** [comment]
Any idea how to fix setupAccess.py? I have to manually refresh the access token once every week.

**Comment by SVendittelli** [comment]
I haven't had a chance to look at it yet, I should hopefully be able to work it out this week

**Comment by SVendittelli** [comment]
Okay, so the problem is that when using `git clone`, the created files and folders belong to `root`. So to make the file changes python needs to be run with super user privileges. I have not yet found a way to do this in any kind of automated manner but here is a temporary fix:

Use `sudo python setupAccess.py` to run setup access, this gives it all it needs to get new tokens.

Start your mirror with `sudo npm start`. This **_SHOULD_** work until I can make python-shell have root privileges.

**Comment by greppie** [comment]
My MM files belong to my user account. The problem was that I startet `setupAccess.py` in a remote shell so it can't open the browser. There was no error message indicating that. Needed super user previleges is not a good idea.

Now I started the script with user privileges directly on the system an it works fine. You solved this issue and I'll close it now.

Thanks a lot again for your help!

**Comment by moshinh** [comment]
> Next thing ist, that setupAccess.py doesnt work or I did not understood how it does. The script start a server at port 8080 but if fitbit redirects to it I get an error that the page is not accessible. However I copied the token from url an put it into tokens.ini. There's only an access token and no refresh token, right?

I am having this same problem, I get a 404 error on the attempt to get my tokens.  I was able to pull the token from the URL, but have no way to get the refresh. Please help, im so close!  Thanks for all of your effort.
