### ISSUE TITLE
Magic Mirror does not load.

### ISSUE THREAD

**Issue by bikerboymohit** [SVendittelli/MMM-fitbit#5]
Below is the information I have in my config.js (client_id and client_secret are dummy here in the below example).

{
    module: 'MMM-fitbit',
    position: 'top_center',
    config: [
        credentials: {
            client_id: 12345,
            client_secret: abcdefg1235hijoklmnopqrstuvwxyz,
        },
        resources: [
            'steps',
            'floors',
            'caloriesOut',
            'distance',
            'activeMinutes',
            'sleep',
            'heart'
        ]
    ]
},

**Comment by Hellangel1987** [comment]
I have also the same problem with the example code.
Any update on this ?

**Comment by SVendittelli** [comment]
Sorry, I haven't been keeping up with this. There is a problem with the file ownership git has over the .ini files. I will hopefully have a look at it this week!

**Comment by Hellangel1987** [comment]
@SVendittelli would be great i switched over to this GIT project because of your module @SVendittelli would be great if we can get a fix *hope* +1:

**Comment by Hellangel1987** [comment]
@SVendittelli @bikerboymohit 

Solved that issue with this Code Line in Config.js

		{
			module: 'MMM-fitbit',
			position: 'top_center',
			config: {
			credentials: {
			client_id: 'YOURID',
			client_secret: 'YOURID',
		},

**Comment by SVendittelli** [comment]
This problem should be addressed in the latest release. Please remake your `.ini` files for changes to take effect.

Feel free to reopen if the problem persists!
