### ISSUE TITLE
Cannot Load Magic Mirror

### ISSUE THREAD

**Issue by Hellangel1987** [SVendittelli/MMM-fitbit#6]
There are issues with your Sample config:

{
	module: 'MMM-fitbit',
	position: 'top_center',
	config: [
		credentials: {
			client_id: <client_id>,
			client_secret: <client_secret>,
		},
		resources: [
			'steps',
			'floors',
			'caloriesOut',
			'distance',
			'activeMinutes',
			'sleep',
			'heart'
		]
	]
},

Magic Mirror cannot load your config.

**Comment by plumcraft** [comment]
Same issue with me. 
The setupAccess.py does not work for me, it hangs...
And running npm start via sudo failed.

>pi@pi:~/MagicMirror $ sudo npm start

> magicmirror@2.0.0 start /home/pi/MagicMirror
> electron js/electron.js

> npm ERR! Linux 4.4.11-v7+
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> npm ERR! node v6.3.1
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> npm ERR! magicmirror@2.0.0 start: `electron js/electron.js`
> npm ERR! Exit status 1`

Looking forward to test your module

**Comment by Hellangel1987** [comment]
@plumcraft 

try my code line

		{
			module: 'MMM-fitbit',
			position: 'top_center',
			config: {
			credentials: {
			client_id: '123456789',
			client_secret: '123456789',
		},

it should work. you have to setup the token.ini on desktop with your raspberry. if you have any other issues come here -> https://forum.magicmirror.builders/topic/214/fitbit 

Regards
Sven

**Comment by SVendittelli** [comment]
This problem should be addressed in the latest release. Please remake your `.ini` files for changes to take effect.

Feel free to reopen if the problem persists!
